import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // categorySidebar: [
  //   {
  //     type: 'category',
  //     label: 'Danh Mục',
  //     items: [
  //       'categories/technical-services',
  //       'categories/medications',
  //       'categories/supplies-goods',
  //     ],
  //   },
  // ],
  // settingSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Thiết Lập',
  //     items: [
  //       'settings/technical-service-pricing',
  //       'settings/medication-supplies-goods-pricing',
  //     ],
  //   },
  // ],
  // receptionSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tiếp Nhận',
  //     items: [
  //       'reception/registration-services',
  //       'reception/payment',
  //       'reception/customer-list',
  //     ],
  //   },
  // ],
  // outpatientExamSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Khám Ngoại Trú',
  //     items: [
  //       'outpatient-examination/vital-signs-measurement',
  //       'outpatient-examination/medicine-examination-yhgd',
  //     ],
  //   },
  // ],
};

export default sidebars;
